openapi: 3.0.0
info:
  title: UMC Study API
  version: 1.0.0
  description: UMC Study API with express, API 설명
  
paths:
  /store/review:
    post:
      tags:
        - Mission
      summary: 가게 리뷰 추가
      parameters:
      - name: store_new_review
        in: body
        required: true
        schema:
          properties:
            review_article:
              type: text
              description: 리뷰내용
              example: 이 가게는 맛있다.
      responses:
        '200':
          description: 가게에 리뷰 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  'review_article': '이 가게는 맛있다.'
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.




